### ISSUE TITLE
How to train SVR

### ISSUE THREAD

**Issue by Leerw** [jchibane/if-net#12]
I am confused with how to train if-net in SVR mode, since the human reconstruction data in not available now, I want to apply if-net to my own one-side-view point cloud.
In voxelized_data_shapenet.py
https://github.com/jchibane/if-net/blob/f1d7050a0e1779fda4aabc9f56731a4ba5c9d9db/models/data/voxelized_data_shapenet.py#L52-L70

Should I change the voxelized_point_cloud*.npz to voxelized_oneside_point_cloud*.npz created from one-side-view point cloud and keep the boundary_sample.npz as the same created from ground truth mesh?

**Comment by jchibane** [comment]
Hi,

that's exactly correct. :)

Best,
Julian

**Comment by Leerw** [comment]
I trained a tiny SVR using one-side(at the front view of each model) view shapenet "Lamp" category, around 2000 models for training and 100 models for validation, all data processing were done the same as point cloud completion task,  128**3 and using ShapeNetPoints 6 layer module, but the training procedure totally overfit quickly at epoch 6. All the hyper parameters are the default.
Here is an example, could you give me some advice?
![image](https://user-images.githubusercontent.com/29098373/90612557-cb005a80-e23a-11ea-815d-454a2dec7f74.png)

**Comment by jchibane** [comment]
Hi Leerw,

so your model has a validation minimum at epoch 6?

I haven't tried on laps with SVR but only humans. The bumps in the lamp 
seem counter intuitive though, I'd have assumed a smoother completion.

Please try the SVR model for your task - that's the one I used for 
humans.

Also, you could check the performance on a different category. I 
remember the lamps category is quite diverse and there might not be so 
much common object knowleadge. This might make it harder to complete 
unknown structures. Maybe try cars as a sanity check.

Do you use enough points from the single view? We used around 5000 
points input.

Best,
Julian


Am 2020-08-19 10:45, schrieb leerw:
