### ISSUE TITLE
Problem with building dependencies

### ISSUE THREAD

**Issue by weders** [jchibane/if-net#13]
Hi Julian,

Thanks for providing the code for IF-Net. I run into a compiling issue for the dependencies. 

I fixed it with the following two changes to the setup.py file in libmesh:

added `import numpy`
changed `setup(...)` to `setup(name = 'libmesh', ext_modules = cythonize("*.pyx"), include_dirs=[numpy.get_include()])`

Might be helpful for other users of the project.

Cheers!

**Comment by weders** [comment]
Furthermore, the following line in implicit_waterproofing.py caused an error:

`from data_processing.libmesh.inside_mesh import check_mesh_contains`

changing it to 

`from libmesh.inside_mesh import check_mesh_contains`

fixed it.

**Comment by jchibane** [comment]
Thanks a lot, that might have happened while rearranging the project for release. I'll check it out and update the project. Thanks for the contribution!
