### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by DuziKim** [jchibane/if-net#14]
Hi. Thank you for great work, Julian!

I need your advice for my research.

I want to reconstruct human mesh data as implicit representation.

but this mesh has big hole.

I'm thinking these days how i can make occupancy data from this.

Can Your watertight mesh construction algorithm make this as a filled occupancy grid?

or do you think any other good ways for this?

thank you again!

**Comment by jchibane** [comment]
Hi @DuziKim ,

yes, our preprocessing script can handle holes up to a certain amount. I used it on human data, where often the feet had no bottom. The "implicit waterproofing" function (described in the supplementary paper) could handle such holes very well.

See https://github.com/jchibane/if-net/blob/master/data_processing/implicit_waterproofing.py#L31

You give it a mesh (as trimesh object) and a point in 3D space. The output will be if this point is inside or outside of your object, which is what you need to train our IF-Nets.
To see if it creates reasonable watertighting on your data you can do the following:
- create points in 3D, which lay on a 3D grid enclosing the object (something along the lines of https://github.com/jchibane/if-net/blob/master/data_processing/implicit_waterproofing.py#L70)
- for each point, let the implicit waterproofing algorithm decide if its inside or outside
- now run marching cubes, to reconstruct a surface from the inside/ouside grid: if it looks good, you are ready to use IF-Nets.

Hope that helps!

Best,
Julian

**Comment by DuziKim** [comment]
Great, but I concern about "certain amount". I trying to apply this on CoMA mesh data, it has big hole bottom of neck..! 
Anyway, thank you!!
