### ISSUE TITLE
Script to test pretrained model 

### ISSUE THREAD

**Issue by arnabdeypolimi** [jchibane/if-net#20]
Can you please provide a script to use your pretrained models for prediction?

**Comment by jchibane** [comment]
Hi @arnabdeypolimi,

with minor changes to the checkpoint loading https://github.com/jchibane/if-net/blob/f1875934dc1fb5bc19e8977f29292d1b40af8a1d/models/generation.py#L92 or by simply setting up an experiment folder incorporating the checkpoint you should be able to run the pre-trained models.
We plan to integrate a more convenient official solution in a future update but can't promise a date yet. A PR is very welcome!

Best,
Julian

**Comment by arnabdeypolimi** [comment]
Hello @jchibane 

Thanks for your response. 

Btw do know how solve this error
`Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
`
I am getting this error while running 
`python data_processing/convert_to_scaled_off.py
`
I have tried both meshlabserver commands mentioned in convert_to_scaled_off.py

Do you have any suggestion?

**Comment by jchibane** [comment]
Hi,

I have not seen this issue so far. I used MehLab v1.3.2 - this might be worth trying.

Best,
Julian

**Comment by arnabdeypolimi** [comment]
Hi @jchibane,

I have tried that particular version also but still having same error. Is it possible for you to make a docker image of the code? 

Thank you,
Arnab Dey

**Comment by jchibane** [comment]
Hi,

I think a possible way out might be to use a different library to convert from .OBJ to .OFF .
If I remember correctly I found trimesh might be an option!

Best,
Julian

**Comment by arnabdeypolimi** [comment]
> Hi,
> 
> I think a possible way out might be to use a different library to convert from .OBJ to .OFF .
> If I remember correctly I found trimesh might be an option!
> 
> Best,
> Julian

I have managed to solve the conversion problem. I hardcoded the conversion with python script without using any library. It is slower than the library but it worked

**Comment by arnabdeypolimi** [comment]
@jchibane can you please tell me how did you generate the demo gif of the mesh and point cloud?  I mean the rotating video of meshes on the readme

**Comment by jchibane** [comment]
We did this manually via blender! :)
