### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'val_data_iterator'

### ISSUE THREAD

**Issue by cathylacus** [jchibane/if-net#21]
I can‘t find the val_data_iterator，The code is
training.py
def compute_val_loss(self):
        self.model.eval()

        sum_val_loss = 0
        num_batches = 15
        for _ in range(num_batches):
            try:
                val_batch = self.val_data_iterator.next()
            except:
                self.val_data_iterator = self.val_dataset.get_loader().__iter__()
                val_batch = self.val_data_iterator.next()

            sum_val_loss += self.compute_loss( val_batch).item()

        return sum_val_loss / num_batches

**Comment by Rainfalllen** [comment]
I has the same question. Could you tell how to fix it?

**Comment by supgy** [comment]
have you solved this problem? I face the same question. Hope your rely.thanks a lot
