### ISSUE TITLE
Cannot find reference 'voxelize' in 'imported module data_processing.libvoxelize'

### ISSUE THREAD

**Issue by ljq2020** [jchibane/if-net#29]
hi,
When I run `python data_processing/voxelized_pointcloud_sampling.py -res 128 -num_points 300`, I met this problem:

Traceback (most recent call last):
  File "data_processing/voxelized_pointcloud_sampling.py", line 1, in <module>
    import implicit_waterproofing as iw
  File "/home/ubuntu/Documents/if-net/data_processing/implicit_waterproofing.py", line 3, in <module>
    from data_processing.libmesh.inside_mesh import check_mesh_contains
ModuleNotFoundError: No module named 'data_processing'
 but the data_processing file exists in the project.

**Comment by ljq2020** [comment]
Cannot find reference 'voxelize' in 'imported module data_processing.libvoxelize' 

Is the `voxelize.py` missing from the `data_processing/ libvoxelize`?

**Comment by ljq2020** [comment]
`Cannot find reference 'voxelize' in 'imported module data_processing.libvoxelize'`

Is the voxelize.py missing from the data_processing/ libvoxelize?

**Comment by jchibane** [comment]
Hi @ljq2020 ,

I guess something went wrong when installing the library - please follow the 'install' instructions in the README file.

Best,
Julian

**Comment by jiaqiAA** [comment]
Hi,

I follow the 'install' instructions, when I run `python setup.py build_ext --inplace`, the result is as follows:
![1](https://user-images.githubusercontent.com/63891270/113383897-7966a380-93b7-11eb-8e6d-7a87ba39e20f.png)
Do you know how to deal with it?

**Comment by ljq2020** [comment]
I find two errors in `inside_mesh.py`
![2](https://user-images.githubusercontent.com/63891270/113385164-26422000-93ba-11eb-92b4-60dfc6e8e7d4.png)

**Comment by jiaqiAA** [comment]
I found a error in `inside_mesh.py`
![2](https://user-images.githubusercontent.com/63891270/113385255-57baeb80-93ba-11eb-8fc0-edfa39021309.png)

**Comment by Yxs-160** [comment]
> hi, When I run `python data_processing/voxelized_pointcloud_sampling.py -res 128 -num_points 300`, I met this problem:
> 
> Traceback (most recent call last): File "data_processing/voxelized_pointcloud_sampling.py", line 1, in import implicit_waterproofing as iw File "/home/ubuntu/Documents/if-net/data_processing/implicit_waterproofing.py", line 3, in from data_processing.libmesh.inside_mesh import check_mesh_contains ModuleNotFoundError: No module named 'data_processing' but the data_processing file exists in the project.

Hi, Have you solved this problem? I meet the same problem with you

**Comment by Bingoang** [comment]
Maybe you could try to add your project path to the voxelized_pointcloud_sampling.py.
Add the following code at the top of the file:
`import sys`
`sys.path.append('/XXXX/if-net-master')`

**Comment by Yxs-160** [comment]
> Maybe you could try to add your project path to the voxelized_pointcloud_sampling.py. Add the following code at the top of the file: `import sys` `sys.path.append('/XXXX/if-net-master')`

oh! I have tried it, and it's valid. Thank you very much!
