### ISSUE TITLE
Query point p and surrounding points with distance d

### ISSUE THREAD

**Issue by csyhping** [jchibane/if-net#32]
Hi @jchibane , I notice that the value of d is different in models, like 0.035 in ShapeNet32Vox, 0.0722 in SVR. May I ask how is the value of d decided?  Besides, since the convolution has already extract deep features, it should capture features from neighbours already, is it necessary to add additional neighbor points? Thanks.

**Comment by jchibane** [comment]
Hi @csyhping,

the intuition of the displacements is to capture details of the input in a neighboring region of the query point.

The values were decided empirically specifically for the dataset:
the ShapeNet objects are in a bounding box of [-0.5,0.5]**3 and the Humans dataset for SVR in a box of approximatly double the size - this also explains why for SVR the displacement is roughly doubled.

Note: We found adding these displacements improves results, but also causes a significant increase in computational cost. In case training/inference speed or GPU memory is more important than a slight improvement in quality, all displacements can be neglected completely.

Best,
Julian

**Comment by csyhping** [comment]
Hi @jchibane , thanks for your reply. I'm still a little confused. Take ShapeNet32Vox object as an example, the object is in a [-0.5, 0.5] bounding box, is the distance d = 1/32? If so, why it is 0.0722 in ShapeNet128Vox?
