### ISSUE TITLE
About Human Reconstruction

### ISSUE THREAD

**Issue by Minglin-Chen** [jchibane/if-net#33]
I am really interested in your work, especially human reconstruction using implicit function. However, I didn't find any codes and checkpoints for human reconstruction in this repo. Will you plan to release the relevant codes and checkpoints in the future?

**Comment by jchibane** [comment]
Hi @MinglinChen94 ,

we do not offer a dataset or checkpoint, but we do offer the code to run and train your model in this repository.
Please follow the data preprocessing, training, and generation as described if you have your own data.

Best,
Julian
