### ISSUE TITLE
about the trained models

### ISSUE THREAD

**Issue by littlesaohuo** [jchibane/if-net#4]
Hi,

I really appreciate your great work.  I am following the commands to prepare data and train, and it has taking a long time.
Will you release the trained models?  I want to learn the effect first.

Thanks!

**Comment by nauman-tintash** [comment]
Hi,

I was also trying to figure this out, we can probably afford to train the model once but if you're experimenting with different parameters, then it might not be feasible to do it over and over again. 

One thing I tried while experimenting was to train on smaller datasets initially. For example, my use case was related to furniture so I only extracted and trained on the subset of Shapenet with data of Chairs. 

But, eventually, it would be helpful if somebody posted a trained model. I will try to share mine but I haven't gotten around to training on the full dataset yet.

**Comment by jchibane** [comment]
Hi,

yes, I plan to release the models.
However, I will prepare this in two weeks probably.

Best,
Julian

**Comment by Leerw** [comment]
The pretrained model cannot be extracted as follows;

tar -xvf checkpoint_epoch_23.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by jchibane** [comment]
Hi,

the .tar file is already the checkpoint used by pytorch, i.e. you don't have to unzip it - but you can read it in directly.
If I find some time in the future, I might add functionality for loading the pretrained models to the master branch. Other than that a PR is of course very welcome.

Best,
Julian
