### ISSUE TITLE
Why does there exist a displacement

### ISSUE THREAD

**Issue by pengsida** [jchibane/if-net#6]
I noticed that there are some displacements in the networks.
For ShapeNet32Vox, the displacement is 0.035: https://github.com/jchibane/if-net/blob/master/models/local_model.py#L40
For other networks, the displacement is 0.0722: https://github.com/jchibane/if-net/blob/master/models/local_model.py#L124
Could you tell me the reason?

**Comment by jchibane** [comment]
Hi,

please check the supplementary (paragraph: "Continuous Feature Extraction") for a detailed description:
https://virtualhumans.mpi-inf.mpg.de/papers/chibane20ifnet/chibane20ifnet_supp.pdf

and let me know if you have further questions!

Best,
Julian

**Comment by pengsida** [comment]
Ok, I get it.
Thanks for your response.
Have a good day!

**Comment by Leerw** [comment]
> Hi,
> 
> please check the supplementary (paragraph: "Continuous Feature Extraction") for a detailed description:
> https://virtualhumans.mpi-inf.mpg.de/papers/chibane20ifnet/chibane20ifnet_supp.pdf
> 
> and let me know if you have further questions!
> 
> Best,
> Julian

Thanks for your impressive work, I just want to know from what reason you select 0.0722 for d rather than any other number, is there some consideration besides the supp and paper?

**Comment by Leerw** [comment]
@jchibane

**Comment by jchibane** [comment]
I used for a displacement that looked intuitive for me and measured the distance, it was this value 0.0722 and I took it. Therefore, this is obviously a hyper-parameter that can be optimized. Also, it is a displacement useful for the scale of data used in our experiments. If someone is using other data, for example 10x the size, also the displacement value should be scaled accordingly.

Best,
Julian

**Comment by Leerw** [comment]
> I used a displacement that looked intuitive for me and measured the distance, it was this value 0.0722 and I took it. Therefore, this is obviously a hyper-parameter that can be optimized. Also, it is a displacement useful for the scale of data used in our experiments. If someone is using other data, for example 10x the size, also the displacement value should be scaled accordingly.
> 
> Best,
> Julian

Thanks for your answer.
